### PR TITLE
Remove Ruby 1.9 from CI

### PR DESCRIPTION
**Pull request by amclain**
We're using `require_relative` and a couple other language features that are not compatible with Ruby 1.9, which is causing the CI builds to fail. Instead of hacking the build path to work around this, I think we should just disable testing on 1.9 for now. I'm on the fence about supporting 1.9 at all.

### CODE REVIEW

**Comment by amclain** [comment]
@tweatherford and @tslogan, this is ready for review.

**Comment by tweatherford** [comment]
:+1: Definitely, approved :+1:

**Comment by tslogan** [comment]
:shipit:

**Comment by amclain** [comment]
Ruby 1.9 was officially EOL on Feb 23, 2015 and security fixes are not being backported. That makes the decision pretty easy not to support it.

https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

**Pull request merged**
