### PR TITLE
Implement Character::SkillQueue endpoint

### PR DESCRIPTION
**Pull request by amclain**
For #68

### CODE REVIEW

**Comment by amclain** [comment]
@tslogan ready for review.

**Comment by tslogan** [comment]
Does this also account for this: 

> Time when training will start (or started), or _null if the queue is paused._
> https://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/character/char_skillqueue.html

**Comment by amclain** [comment]
@tslogan it does now :wink: 
Good catch.

**Comment by tslogan** [comment]
:+1:

**Pull request merged**
